openapi: 3.0.1
info:
  title: TIDAL Catalog acceptedTerms playQueues API
  version: 1.10.14
  description: 'Browse TIDAL''s high-fidelity music catalog: albums, artists, tracks, videos, genres, lyrics, credits, and artwork. JSON:API compliant with relationship traversal.'
  x-source: https://tidal-music.github.io/tidal-api-reference/tidal-api-oas.json
servers:
- url: https://openapi.tidal.com/v2
  description: Production
tags:
- name: playQueues
paths:
  /playQueues:
    get:
      description: Retrieves multiple playQueues by available filters, or without if applicable.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get multiple playQueues.
      tags:
      - playQueues
      x-path-item-properties:
        required-access-tier: INTERNAL
    post:
      description: Creates a new playQueue.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Create single playQueue.
      tags:
      - playQueues
      x-path-item-properties:
        required-access-tier: INTERNAL
  /playQueues/{id}:
    delete:
      description: Deletes existing playQueue.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Delete single playQueue.
      tags:
      - playQueues
      x-path-item-properties:
        required-access-tier: INTERNAL
    get:
      description: Retrieves single playQueue by id.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get single playQueue.
      tags:
      - playQueues
      x-path-item-properties:
        required-access-tier: INTERNAL
    patch:
      description: Updates existing playQueue.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Update single playQueue.
      tags:
      - playQueues
      x-path-item-properties:
        required-access-tier: INTERNAL
  /playQueues/{id}/relationships/current:
    get:
      description: Retrieves current relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get current relationship ("to-one").
      tags:
      - playQueues
      x-path-item-properties:
        required-access-tier: INTERNAL
    patch:
      description: Updates current relationship.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Update current relationship ("to-one").
      tags:
      - playQueues
      x-path-item-properties:
        required-access-tier: INTERNAL
  /playQueues/{id}/relationships/future:
    delete:
      description: Deletes item(s) from future relationship.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Delete from future relationship ("to-many").
      tags:
      - playQueues
      x-path-item-properties:
        required-access-tier: INTERNAL
    get:
      description: Retrieves future relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get future relationship ("to-many").
      tags:
      - playQueues
      x-path-item-properties:
        required-access-tier: INTERNAL
    patch:
      description: Updates future relationship.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Update future relationship ("to-many").
      tags:
      - playQueues
      x-path-item-properties:
        required-access-tier: INTERNAL
    post:
      description: Adds item(s) to future relationship.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Add to future relationship ("to-many").
      tags:
      - playQueues
      x-path-item-properties:
        required-access-tier: INTERNAL
  /playQueues/{id}/relationships/owners:
    get:
      description: Retrieves owners relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get owners relationship ("to-many").
      tags:
      - playQueues
      x-path-item-properties:
        required-access-tier: INTERNAL
  /playQueues/{id}/relationships/past:
    get:
      description: Retrieves past relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get past relationship ("to-many").
      tags:
      - playQueues
      x-path-item-properties:
        required-access-tier: INTERNAL
components:
  securitySchemes:
    Authorization_Code_PKCE:
      description: See https://developer.tidal.com/documentation/authorization/authorization-authorization-code
      flows:
        authorizationCode:
          authorizationUrl: https://login.tidal.com/authorize
          scopes:
            collection.read: Read access to a user's "My Collection".
            collection.write: Write access to a user's "My Collection".
            entitlements.read: Read access to what functionality a user is entitled to access on TIDAL, such as whether they can stream music, use DJ add-ons and similar.
            playback: Required to play media content and control playback.
            playlists.read: Required to list playlists created by a user.
            playlists.write: Write access to a user's playlists.
            r_usr: Read access to all end user data
            recommendations.read: Read access to a user’s personal recommendations.
            search.read: Required to read personalized search results.
            search.write: Required to update personalized search results, e.g. delete search history.
            user.read: Read access to a user's account information, such as country and email address.
            w_usr: Write user
          tokenUrl: https://auth.tidal.com/v1/oauth2/token
          x-scopes-required-access-tier:
            collection.read: THIRD_PARTY
            collection.write: THIRD_PARTY
            entitlements.read: THIRD_PARTY
            playback: THIRD_PARTY
            playlists.read: THIRD_PARTY
            playlists.write: THIRD_PARTY
            r_usr: INTERNAL
            recommendations.read: THIRD_PARTY
            search.read: THIRD_PARTY
            search.write: THIRD_PARTY
            user.read: THIRD_PARTY
            w_usr: INTERNAL
      type: oauth2
    Client_Credentials:
      description: See https://developer.tidal.com/documentation/authorization/authorization-client-credentials
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://auth.tidal.com/v1/oauth2/token
      type: oauth2
