openapi: 3.0.1
info:
  title: TIDAL Catalog API
  version: 1.10.14
  description: 'Browse TIDAL''s high-fidelity music catalog: albums, artists, tracks, videos, genres, lyrics, credits, and
    artwork. JSON:API compliant with relationship traversal.'
  x-source: https://tidal-music.github.io/tidal-api-reference/tidal-api-oas.json
servers:
- url: https://openapi.tidal.com/v2
  description: Production
paths:
  /albumStatistics:
    get:
      description: Retrieves multiple albumStatistics by available filters, or without if applicable.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get multiple albumStatistics.
      tags:
      - albumStatistics
      x-path-item-properties:
        required-access-tier: INTERNAL
  /albumStatistics/{id}:
    get:
      description: Retrieves single albumStatistic by id.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get single albumStatistic.
      tags:
      - albumStatistics
      x-path-item-properties:
        required-access-tier: INTERNAL
  /albumStatistics/{id}/relationships/owners:
    get:
      description: Retrieves owners relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get owners relationship ("to-many").
      tags:
      - albumStatistics
      x-path-item-properties:
        required-access-tier: INTERNAL
  /albums:
    get:
      description: Retrieves multiple albums by available filters, or without if applicable.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get multiple albums.
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
    post:
      description: Creates a new album.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Create single album.
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: INTERNAL
  /albums/{id}:
    delete:
      description: Deletes existing album.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Delete single album.
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: INTERNAL
    get:
      description: Retrieves single album by id.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get single album.
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
    patch:
      description: Updates existing album.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Update single album.
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: INTERNAL
  /albums/{id}/relationships/albumStatistics:
    get:
      description: Retrieves albumStatistics relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get albumStatistics relationship ("to-one").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: INTERNAL
  /albums/{id}/relationships/artists:
    get:
      description: Retrieves artists relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get artists relationship ("to-many").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /albums/{id}/relationships/coverArt:
    get:
      description: Retrieves coverArt relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get coverArt relationship ("to-many").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
    patch:
      description: Updates coverArt relationship.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Update coverArt relationship ("to-many").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: INTERNAL
  /albums/{id}/relationships/genres:
    get:
      description: Retrieves genres relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get genres relationship ("to-many").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: INTERNAL
  /albums/{id}/relationships/items:
    get:
      description: Retrieves items relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get items relationship ("to-many").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
    patch:
      description: Updates items relationship.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Update items relationship ("to-many").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: INTERNAL
  /albums/{id}/relationships/owners:
    get:
      description: Retrieves owners relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get owners relationship ("to-many").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /albums/{id}/relationships/priceConfig:
    get:
      description: Retrieves priceConfig relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get priceConfig relationship ("to-one").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: INTERNAL
  /albums/{id}/relationships/providers:
    get:
      description: Retrieves providers relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get providers relationship ("to-many").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /albums/{id}/relationships/replacement:
    get:
      description: Retrieves replacement relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get replacement relationship ("to-one").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: INTERNAL
  /albums/{id}/relationships/shares:
    get:
      description: Retrieves shares relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get shares relationship ("to-many").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: INTERNAL
  /albums/{id}/relationships/similarAlbums:
    get:
      description: Retrieves similarAlbums relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get similarAlbums relationship ("to-many").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /albums/{id}/relationships/suggestedCoverArts:
    get:
      description: Retrieves suggestedCoverArts relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get suggestedCoverArts relationship ("to-many").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: INTERNAL
  /albums/{id}/relationships/usageRules:
    get:
      description: Retrieves usageRules relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get usageRules relationship ("to-one").
      tags:
      - albums
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /artistBiographies:
    get:
      description: Retrieves multiple artistBiographies by available filters, or without if applicable.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get multiple artistBiographies.
      tags:
      - artistBiographies
      x-path-item-properties:
        required-access-tier: INTERNAL
  /artistBiographies/{id}:
    get:
      description: Retrieves single artistBiographie by id.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get single artistBiographie.
      tags:
      - artistBiographies
      x-path-item-properties:
        required-access-tier: INTERNAL
    patch:
      description: Updates existing artistBiographie.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Update single artistBiographie.
      tags:
      - artistBiographies
      x-path-item-properties:
        required-access-tier: INTERNAL
  /artistBiographies/{id}/relationships/owners:
    get:
      description: Retrieves owners relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get owners relationship ("to-many").
      tags:
      - artistBiographies
      x-path-item-properties:
        required-access-tier: INTERNAL
  /artistRoles:
    get:
      description: Retrieves multiple artistRoles by available filters, or without if applicable.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get multiple artistRoles.
      tags:
      - artistRoles
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /artistRoles/{id}:
    get:
      description: Retrieves single artistRole by id.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get single artistRole.
      tags:
      - artistRoles
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /artists:
    get:
      description: Retrieves multiple artists by available filters, or without if applicable.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get multiple artists.
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
    post:
      description: Creates a new artist.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Create single artist.
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: INTERNAL
  /artists/{id}:
    get:
      description: Retrieves single artist by id.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get single artist.
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
    patch:
      description: Updates existing artist.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Update single artist.
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: INTERNAL
  /artists/{id}/relationships/albums:
    get:
      description: Retrieves albums relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get albums relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /artists/{id}/relationships/biography:
    get:
      description: Retrieves biography relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get biography relationship ("to-one").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /artists/{id}/relationships/followers:
    get:
      description: Retrieves followers relationship.
      security:
      - Authorization_Code_PKCE: []
      summary: Get followers relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: INTERNAL
  /artists/{id}/relationships/following:
    delete:
      description: Deletes item(s) from following relationship.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Delete from following relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: INTERNAL
    get:
      description: Retrieves following relationship.
      security:
      - Authorization_Code_PKCE: []
      summary: Get following relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: INTERNAL
    post:
      description: Adds item(s) to following relationship.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Add to following relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: INTERNAL
  /artists/{id}/relationships/owners:
    get:
      description: Retrieves owners relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get owners relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /artists/{id}/relationships/profileArt:
    get:
      description: Retrieves profileArt relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get profileArt relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
    patch:
      description: Updates profileArt relationship.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Update profileArt relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: INTERNAL
  /artists/{id}/relationships/radio:
    get:
      description: Retrieves radio relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get radio relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /artists/{id}/relationships/roles:
    get:
      description: Retrieves roles relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get roles relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /artists/{id}/relationships/similarArtists:
    get:
      description: Retrieves similarArtists relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get similarArtists relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /artists/{id}/relationships/trackProviders:
    get:
      description: Retrieves trackProviders relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get trackProviders relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /artists/{id}/relationships/tracks:
    get:
      description: Retrieves tracks relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get tracks relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /artists/{id}/relationships/videos:
    get:
      description: Retrieves videos relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get videos relationship ("to-many").
      tags:
      - artists
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /artworks:
    get:
      description: Retrieves multiple artworks by available filters, or without if applicable.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get multiple artworks.
      tags:
      - artworks
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
    post:
      description: Creates a new artwork.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Create single artwork.
      tags:
      - artworks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /artworks/{id}:
    get:
      description: Retrieves single artwork by id.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get single artwork.
      tags:
      - artworks
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /artworks/{id}/relationships/owners:
    get:
      description: Retrieves owners relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get owners relationship ("to-many").
      tags:
      - artworks
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /credits:
    get:
      description: Retrieves multiple credits by available filters, or without if applicable.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get multiple credits.
      tags:
      - credits
      x-path-item-properties:
        required-access-tier: INTERNAL
  /credits/{id}:
    get:
      description: Retrieves single credit by id.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get single credit.
      tags:
      - credits
      x-path-item-properties:
        required-access-tier: INTERNAL
  /credits/{id}/relationships/artist:
    get:
      description: Retrieves artist relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get artist relationship ("to-one").
      tags:
      - credits
      x-path-item-properties:
        required-access-tier: INTERNAL
  /credits/{id}/relationships/category:
    get:
      description: Retrieves category relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get category relationship ("to-one").
      tags:
      - credits
      x-path-item-properties:
        required-access-tier: INTERNAL
  /genres:
    get:
      description: Retrieves multiple genres by available filters, or without if applicable.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get multiple genres.
      tags:
      - genres
      x-path-item-properties:
        required-access-tier: INTERNAL
  /genres/{id}:
    get:
      description: Retrieves single genre by id.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get single genre.
      tags:
      - genres
      x-path-item-properties:
        required-access-tier: INTERNAL
  /lyrics:
    get:
      description: Retrieves multiple lyrics by available filters, or without if applicable.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get multiple lyrics.
      tags:
      - lyrics
      x-path-item-properties:
        required-access-tier: INTERNAL
    post:
      description: Creates a new lyric.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Create single lyric.
      tags:
      - lyrics
      x-path-item-properties:
        required-access-tier: INTERNAL
  /lyrics/{id}:
    delete:
      description: Deletes existing lyric.
      security:
      - Authorization_Code_PKCE: []
      summary: Delete single lyric.
      tags:
      - lyrics
      x-path-item-properties:
        required-access-tier: INTERNAL
    get:
      description: Retrieves single lyric by id.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get single lyric.
      tags:
      - lyrics
      x-path-item-properties:
        required-access-tier: INTERNAL
    patch:
      description: Updates existing lyric.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Update single lyric.
      tags:
      - lyrics
      x-path-item-properties:
        required-access-tier: INTERNAL
  /lyrics/{id}/relationships/owners:
    get:
      description: Retrieves owners relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get owners relationship ("to-many").
      tags:
      - lyrics
      x-path-item-properties:
        required-access-tier: INTERNAL
  /lyrics/{id}/relationships/track:
    get:
      description: Retrieves track relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get track relationship ("to-one").
      tags:
      - lyrics
      x-path-item-properties:
        required-access-tier: INTERNAL
  /providerOwners:
    get:
      description: Retrieves multiple providerOwners by available filters, or without if applicable.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get multiple providerOwners.
      tags:
      - providerOwners
      x-path-item-properties:
        required-access-tier: INTERNAL
  /providerOwners/{id}/relationships/owners:
    get:
      description: Retrieves owners relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get owners relationship ("to-many").
      tags:
      - providerOwners
      x-path-item-properties:
        required-access-tier: INTERNAL
  /providerOwners/{id}/relationships/provider:
    get:
      description: Retrieves provider relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get provider relationship ("to-one").
      tags:
      - providerOwners
      x-path-item-properties:
        required-access-tier: INTERNAL
  /providerProductInfos:
    get:
      description: Retrieves multiple providerProductInfos by available filters, or without if applicable.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get multiple providerProductInfos.
      tags:
      - providerProductInfos
      x-path-item-properties:
        required-access-tier: INTERNAL
  /providerProductInfos/{id}/relationships/provider:
    get:
      description: Retrieves provider relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get provider relationship ("to-one").
      tags:
      - providerProductInfos
      x-path-item-properties:
        required-access-tier: INTERNAL
  /providerProductInfos/{id}/relationships/subject:
    get:
      description: Retrieves subject relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get subject relationship ("to-one").
      tags:
      - providerProductInfos
      x-path-item-properties:
        required-access-tier: INTERNAL
  /providers:
    get:
      description: Retrieves multiple providers by available filters, or without if applicable.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get multiple providers.
      tags:
      - providers
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /providers/{id}:
    get:
      description: Retrieves single provider by id.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get single provider.
      tags:
      - providers
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /trackStatistics:
    get:
      description: Retrieves multiple trackStatistics by available filters, or without if applicable.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get multiple trackStatistics.
      tags:
      - trackStatistics
      x-path-item-properties:
        required-access-tier: INTERNAL
  /trackStatistics/{id}:
    get:
      description: Retrieves single trackStatistic by id.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get single trackStatistic.
      tags:
      - trackStatistics
      x-path-item-properties:
        required-access-tier: INTERNAL
  /trackStatistics/{id}/relationships/owners:
    get:
      description: Retrieves owners relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get owners relationship ("to-many").
      tags:
      - trackStatistics
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks:
    get:
      description: Retrieves multiple tracks by available filters, or without if applicable.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get multiple tracks.
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
    post:
      description: Creates a new track.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Create single track.
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks/{id}:
    delete:
      description: Deletes existing track.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Delete single track.
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
    get:
      description: Retrieves single track by id.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get single track.
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
    patch:
      description: Updates existing track.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Update single track.
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks/{id}/relationships/albums:
    get:
      description: Retrieves albums relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get albums relationship ("to-many").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
    patch:
      description: Updates albums relationship.
      security:
      - Authorization_Code_PKCE:
        - w_usr
      summary: Update albums relationship ("to-many").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks/{id}/relationships/artists:
    get:
      description: Retrieves artists relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get artists relationship ("to-many").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /tracks/{id}/relationships/credits:
    get:
      description: Retrieves credits relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get credits relationship ("to-many").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks/{id}/relationships/download:
    get:
      description: Retrieves download relationship.
      security:
      - Authorization_Code_PKCE: []
      summary: Get download relationship ("to-one").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks/{id}/relationships/genres:
    get:
      description: Retrieves genres relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get genres relationship ("to-many").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks/{id}/relationships/lyrics:
    get:
      description: Retrieves lyrics relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get lyrics relationship ("to-many").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks/{id}/relationships/metadataStatus:
    get:
      description: Retrieves metadataStatus relationship.
      security:
      - Authorization_Code_PKCE: []
      summary: Get metadataStatus relationship ("to-one").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks/{id}/relationships/owners:
    get:
      description: Retrieves owners relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get owners relationship ("to-many").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /tracks/{id}/relationships/priceConfig:
    get:
      description: Retrieves priceConfig relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get priceConfig relationship ("to-one").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks/{id}/relationships/providers:
    get:
      description: Retrieves providers relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get providers relationship ("to-many").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /tracks/{id}/relationships/radio:
    get:
      description: Retrieves radio relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get radio relationship ("to-many").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /tracks/{id}/relationships/replacement:
    get:
      description: Retrieves replacement relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get replacement relationship ("to-one").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks/{id}/relationships/shares:
    get:
      description: Retrieves shares relationship.
      security:
      - Authorization_Code_PKCE:
        - r_usr
      summary: Get shares relationship ("to-many").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks/{id}/relationships/similarTracks:
    get:
      description: Retrieves similarTracks relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get similarTracks relationship ("to-many").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /tracks/{id}/relationships/sourceFile:
    get:
      description: Retrieves sourceFile relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get sourceFile relationship ("to-one").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /tracks/{id}/relationships/suggestedTracks:
    get:
      description: Retrieves suggestedTracks relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get suggestedTracks relationship ("to-many").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks/{id}/relationships/trackStatistics:
    get:
      description: Retrieves trackStatistics relationship.
      security:
      - Authorization_Code_PKCE: []
      summary: Get trackStatistics relationship ("to-one").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracks/{id}/relationships/usageRules:
    get:
      description: Retrieves usageRules relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get usageRules relationship ("to-one").
      tags:
      - tracks
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /tracksMetadataStatus:
    get:
      description: Retrieves multiple tracksMetadataStatus by available filters, or without if applicable.
      security:
      - Authorization_Code_PKCE: []
      summary: Get multiple tracksMetadataStatus.
      tags:
      - tracksMetadataStatus
      x-path-item-properties:
        required-access-tier: INTERNAL
  /tracksMetadataStatus/{id}:
    get:
      description: Retrieves single tracksMetadataStatu by id.
      security:
      - Authorization_Code_PKCE: []
      summary: Get single tracksMetadataStatu.
      tags:
      - tracksMetadataStatus
      x-path-item-properties:
        required-access-tier: INTERNAL
  /videos:
    get:
      description: Retrieves multiple videos by available filters, or without if applicable.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get multiple videos.
      tags:
      - videos
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /videos/{id}:
    get:
      description: Retrieves single video by id.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get single video.
      tags:
      - videos
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /videos/{id}/relationships/albums:
    get:
      description: Retrieves albums relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get albums relationship ("to-many").
      tags:
      - videos
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /videos/{id}/relationships/artists:
    get:
      description: Retrieves artists relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get artists relationship ("to-many").
      tags:
      - videos
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /videos/{id}/relationships/credits:
    get:
      description: Retrieves credits relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get credits relationship ("to-many").
      tags:
      - videos
      x-path-item-properties:
        required-access-tier: INTERNAL
  /videos/{id}/relationships/providers:
    get:
      description: Retrieves providers relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get providers relationship ("to-many").
      tags:
      - videos
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /videos/{id}/relationships/replacement:
    get:
      description: Retrieves replacement relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get replacement relationship ("to-one").
      tags:
      - videos
      x-path-item-properties:
        required-access-tier: INTERNAL
  /videos/{id}/relationships/similarVideos:
    get:
      description: Retrieves similarVideos relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get similarVideos relationship ("to-many").
      tags:
      - videos
      x-path-item-properties:
        required-access-tier: INTERNAL
  /videos/{id}/relationships/suggestedVideos:
    get:
      description: Retrieves suggestedVideos relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get suggestedVideos relationship ("to-many").
      tags:
      - videos
      x-path-item-properties:
        required-access-tier: INTERNAL
  /videos/{id}/relationships/thumbnailArt:
    get:
      description: Retrieves thumbnailArt relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get thumbnailArt relationship ("to-many").
      tags:
      - videos
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
  /videos/{id}/relationships/usageRules:
    get:
      description: Retrieves usageRules relationship.
      security:
      - Client_Credentials: []
      - Authorization_Code_PKCE: []
      summary: Get usageRules relationship ("to-one").
      tags:
      - videos
      x-path-item-properties:
        required-access-tier: THIRD_PARTY
components:
  securitySchemes:
    Authorization_Code_PKCE:
      description: See https://developer.tidal.com/documentation/authorization/authorization-authorization-code
      flows:
        authorizationCode:
          authorizationUrl: https://login.tidal.com/authorize
          scopes:
            collection.read: Read access to a user's "My Collection".
            collection.write: Write access to a user's "My Collection".
            entitlements.read: Read access to what functionality a user is entitled to access on TIDAL, such as whether they
              can stream music, use DJ add-ons and similar.
            playback: Required to play media content and control playback.
            playlists.read: Required to list playlists created by a user.
            playlists.write: Write access to a user's playlists.
            r_usr: Read access to all end user data
            recommendations.read: "Read access to a user\u2019s personal recommendations."
            search.read: Required to read personalized search results.
            search.write: Required to update personalized search results, e.g. delete search history.
            user.read: Read access to a user's account information, such as country and email address.
            w_usr: Write user
          tokenUrl: https://auth.tidal.com/v1/oauth2/token
          x-scopes-required-access-tier:
            collection.read: THIRD_PARTY
            collection.write: THIRD_PARTY
            entitlements.read: THIRD_PARTY
            playback: THIRD_PARTY
            playlists.read: THIRD_PARTY
            playlists.write: THIRD_PARTY
            r_usr: INTERNAL
            recommendations.read: THIRD_PARTY
            search.read: THIRD_PARTY
            search.write: THIRD_PARTY
            user.read: THIRD_PARTY
            w_usr: INTERNAL
      type: oauth2
    Client_Credentials:
      description: See https://developer.tidal.com/documentation/authorization/authorization-client-credentials
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://auth.tidal.com/v1/oauth2/token
      type: oauth2
